version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "/app/dist"
      - "./api:/app"
    depends_on:
      - database
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1337:80"
    depends_on:
      - api
  database:
    image: postgres:14.1-bullseye
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/dash_pg_data/
      POSTGRES_NAME: ${DB}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPWD}
    ports:
      - "${DBPORT}:${DBPORT}"
    volumes:
      - ~/pgdata_hunt:/var/lib/postgresql/data/
