version: "3.9"

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1337:80"
  database:
    image: postgres:14.1-bullseye
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/dash_pg_data/
      POSTGRES_NAME: ${DB}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPWD}
    ports:
      - "${DBPORT}:${DBPORT}"
    volumes:
      - ~/pgdata_hunt:/var/lib/postgresql/data/

    #volumes:
    #  - nginx_conf:/etc/nginx/sites
    #  - letsencrypt_certs:/etc/letsencrypt
    #  - certbot_acme_challenge:/var/www/certbot
    #depends_on:
    #  - api
    #environment:
    #  PORT: "80"
#  certbot:
#    build: ./certbot
#    image: evgeniy-khyst/certbot
#    env_file:
#      - .env
#    volumes:
#      - letsencrypt_certs:/etc/letsencrypt
#      - certbot_acme_challenge:/var/www/certbot
#volumes:
#  nginx_conf: 
#  letsencrypt_certs: 
#  certbot_acme_challenge: 
